import fs from "node:fs";
import path from "node:path";

export type ImageVariant = { width: number; path: string };
export type ManifestEntry = {
  key: string;
  width: number;
  height: number;
  variants: ImageVariant[];
  fallback: string;
};

const MANIFEST_PATH = path.join(process.cwd(), "public", "images", "generated", "manifest.json");

let cache: Record<string, ManifestEntry> | null = null;

/**
 * Reads the responsive-image manifest generated by scripts/optimize-images.mjs.
 * Returns {} if no images have been processed yet (nothing to look up) —
 * callers should fall back to rendering the raw src in that case.
 */
export function getImageManifest(): Record<string, ManifestEntry> {
  if (cache && process.env.NODE_ENV === "production") return cache;
  if (!fs.existsSync(MANIFEST_PATH)) return {};
  const parsed = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8")) as Record<string, ManifestEntry>;
  cache = parsed;
  return parsed;
}

export function getManifestEntry(key: string): ManifestEntry | undefined {
  return getImageManifest()[key];
}
