"use client";

import { useEffect, useRef } from "react";

/**
 * Mounts Pagefind's bundled search UI. Pagefind's assets (/pagefind/*) are
 * generated by a post-build step (`npm run build` runs `pagefind --site out`
 * after `next build` — see package.json) and don't exist in `next dev`, so
 * this fails soft locally.
 */
export function PagefindSearch() {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    let cancelled = false;

    async function mount() {
      try {
        // @ts-expect-error -- generated at build time, not a package dependency
        await import(/* webpackIgnore: true */ "/pagefind/pagefind-ui.js");
        if (cancelled || !ref.current) return;
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        new (window as any).PagefindUI({ element: ref.current, showSubResults: true });
      } catch {
        if (!cancelled && ref.current) {
          ref.current.textContent =
            "Search is available on the deployed site (index is generated at build time).";
        }
      }
    }

    mount();
    return () => {
      cancelled = true;
    };
  }, []);

  return <div ref={ref} id="search" />;
}
